### ISSUE TITLE
When will open source be available？

### ISSUE THREAD

**Issue by 1haomingtian** [youngwanLEE/MPViT#2]
When will open source be available？

**Comment by youngwanLEE** [comment]
I already finished the preparation of the code release and now am waiting for the approval in our research center.
Please stay tune :)

**Comment by youngwanLEE** [comment]
@1haomingtian 
We release the code and weights. 
Please re-open this issue if you have more questions.

**Comment by 1haomingtian** [comment]
Thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "youngwanLEE/MPViT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月14日(星期五) 中午11:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [youngwanLEE/MPViT] When will open source be available？ (Issue #2)





 
@1haomingtian
 We release the code and weights.
 Please re-open this issue if you have more questions.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
