### ISSUE TITLE
Some details on the implementation.

### ISSUE THREAD

**Issue by ChongjianGE** [youngwanLEE/MPViT#3]
Hi @youngwanLEE.

Thanks for the great work.  After reading the paper, I have some questions about the implementation details. One of the questions is that whether you have used the **Relative Position Encoding** in the transformer architecture design as Coat [(Code here)](https://github.com/mlpc-ucsd/CoaT/blob/cc33830b3d83480119865d7db334a5207d52277a/src/models/coat.py#L60-L116). I found that discarding the relative position encoding in Factorized Attention leads to a significant acc drop.

Looking forward to your reply. Thx.

**Comment by youngwanLEE** [comment]
@ChongjianGE Thanks for your interest in our work.

We also the Relative position encoding. We follow the same implementation of CoaT.

We will release the whole code and trained weights soon.

Stay tuned :)

**Comment by youngwanLEE** [comment]
@ChongjianGE 
We release the code and weights. 
Please re-open this issue if you have more questions.
