### ISSUE TITLE
Demo for visualization?

### ISSUE THREAD

**Issue by zobeirraisi** [youngwanLEE/MPViT#4]
Thanks for the effort and releasing the code, can you please provide a demo for the detection part?

**Comment by youngwanLEE** [comment]
@zobeirraisi 
Hi, thanks for your interest.

So far we don't have a plan to add demo codes, but when we have enough time, we'll add the demo program.

You can also easily implement the demo code by following the [instruction of detectron2](https://github.com/facebookresearch/detectron2/tree/main/demo).

You try it first and if you run into any problems, please re-open this issue.
